### test index page
GET http://localhost:8080/Cargo.toml
### test index page
GET http://localhost:8080/abc.txt

### Test static file with tower-http
GET http://localhost:8080/tower/fixtures/ed25519.pk
